services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD
      POSTGRES_USER: process.env.POSTGRES_USER
      POSTGRES_DB: process.env.POSTGRES_DB
    ports:
      - 5431:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: